### ISSUE TITLE
Add Avatar

### ISSUE THREAD

**Issue by MatsievichSasha** [MatsievichSasha/homepage#9]

**Comment by OlesiaMatsivich** [comment]
<div class="avatar-wrapper">
  <object class="avatar" data="./assets/images/avatar.svg" role="img" aria-label="My profile picture">
![405-4052007_donald-trump-png-image-donald-trump-caricature-png](https://user-images.githubusercontent.com/77269163/104292610-b6607f80-54c5-11eb-8af5-43ea5e04c2da.png)

</object>
